#!/usr/bin/env python3
"""
TP-CAN-2I  Mechanical / Fab Gerber + Excellon generator
=========================================================
Produces a manufacturer-ready (but copper-incomplete) Gerber set that
honestly represents what exists in the KiCad MECHANICAL STARTING BOARD:

  * Board outline (70 x 50 mm, R3 rounded corners)          -> Edge.Cuts
  * Two isolation milling slots (under U9/U10)               -> Edge.Cuts
  * 4x M3 NPTH mounting holes Ø3.2 mm                       -> NPTH.drl
  * Silkscreen: branding, isolation-barrier line, mtg rings  -> F.Silkscreen
  * Copper / mask layers: VALID RS-274X headers, NO features -> placeholder
  * Gerber Job JSON                                           -> .gbrjob
  * Layer map + fab README

COPPER AND SOLDERMASK LAYERS ARE INTENTIONAL PLACEHOLDERS.
They carry only a valid RS-274X header and M02* end-of-file marker.
Complete them by running  File > Fabrication Outputs > Gerbers  inside
KiCad after schematic capture, footprint assignment, placement, and routing.

RS-274X format used:  %FSLAX46Y46*%  (metric, 4 integer / 6 decimal digits)
Coordinate unit: mm × 1 000 000  as a signed integer.
"""

import math
import zipfile
import json
import os
import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).parent.resolve()
OUT = SCRIPT_DIR          # output next to this script inside Hardware/Gerbers/

# ---------------------------------------------------------------------------
# Board geometry (from generate_board.py)
# ---------------------------------------------------------------------------
W, H  = 70.0, 50.0   # board width / height  (mm)
R     = 3.0           # corner radius
K     = R * (1 - math.sqrt(0.5))   # = R*(1-1/√2) ≈ 0.8787 mm

MH = [(4.0, 4.0), (66.0, 4.0), (4.0, 46.0), (66.0, 46.0)]  # NPTH centres
MH_D = 3.2           # NPTH drill diameter (mm)
MH_SILK_R = 3.0      # silk ring outer diameter (mm) -- ring drawn at this radius

# Isolation milling slots  [x0,y0, x1,y1]
SLOTS = [
    (57.3,  8.5, 58.7, 15.5),
    (57.3, 29.5, 58.7, 36.5),
]

# ---------------------------------------------------------------------------
# RS-274X helpers
# ---------------------------------------------------------------------------
SCALE = 1_000_000   # mm → 4.6 integer

def c(v: float) -> int:
    """Convert mm to RS-274X 4.6 integer coordinate."""
    return round(v * SCALE)

def coord(x: float, y: float) -> str:
    """Format X/Y coordinate pair."""
    return f"X{c(x)}Y{c(y)}"

def gerber_header(file_function: str, polarity: str = "Positive") -> list[str]:
    """Return standard RS-274X preamble lines (as list, no newlines yet)."""
    return [
        "%FSLAX46Y46*%",
        "%MOMM*%",
        f"%TF.FileFunction,{file_function}*%",
        f"%TF.FilePolarity,{polarity}*%",
        "%TF.SameCoordinates,Original*%",
        "G04 --- Generated by TP-CAN-2I generate_gerbers.py ---*",
    ]

def gerber_footer() -> list[str]:
    return ["M02*"]

def apt(code: int, shape: str, params: str) -> str:
    """Aperture definition line, e.g. apt(10,'C','0.150')."""
    return f"%ADD{code}{shape},{params}*%"

# ---------------------------------------------------------------------------
# 1. Edge Cuts  (TP-CAN-2I-Edge_Cuts.gm1)
# ---------------------------------------------------------------------------
def build_edge_cuts() -> str:
    lines = gerber_header("Profile,NP")
    # Apertures: outline (0.12 mm) + slot outline (0.12 mm) — same width
    lines += [
        apt(10, "C", "0.120"),  # outline / slot line width
        "G04 Select outline aperture*",
        "D10*",
        "G04 --- Board outline: straight edges + G03 arcs for rounded corners ---*",
        "G75*",   # multi-quadrant arc mode (required before G02/G03)
    ]

    # Helper: draw a line segment
    def line(x0, y0, x1, y1):
        return [
            f"{coord(x0, y0)}D02*",   # move to start
            f"{coord(x1, y1)}D01*",   # draw
        ]

    # Helper: draw a G03 (CCW) arc
    # start→end with centre offset I/J (from current position = start)
    def arc_ccw(sx, sy, ex, ey, cx, cy):
        i = round((cx - sx) * SCALE)
        j = round((cy - sy) * SCALE)
        return [
            f"{coord(sx, sy)}D02*",
            f"G03{coord(ex, ey)}I{i}J{j}D01*",
        ]

    # ---- Four straight edges (KiCad coordinate system: Y increases downward) ----
    # Top edge:  (R,0) → (W-R, 0)
    lines += line(R, 0, W - R, 0)
    # Top-right arc: (W-R,0) → (W,R)  centre=(W,0)
    lines += arc_ccw(W - R, 0, W, R, W, 0)
    # Right edge: (W,R) → (W, H-R)
    lines += line(W, R, W, H - R)
    # Bottom-right arc: (W,H-R) → (W-R,H)  centre=(W,H)
    lines += arc_ccw(W, H - R, W - R, H, W, H)
    # Bottom edge: (W-R,H) → (R,H)
    lines += line(W - R, H, R, H)
    # Bottom-left arc: (R,H) → (0,H-R)  centre=(0,H)
    lines += arc_ccw(R, H, 0, H - R, 0, H)
    # Left edge: (0,H-R) → (0,R)
    lines += line(0, H - R, 0, R)
    # Top-left arc: (0,R) → (R,0)  centre=(0,0)
    lines += arc_ccw(0, R, R, 0, 0, 0)

    # ---- Isolation milling slots (rectangular outlines on Edge.Cuts) ----
    lines += ["G04 --- Isolation milling slots ---*"]
    for (x0, y0, x1, y1) in SLOTS:
        lines += line(x0, y0, x1, y0)   # top
        lines += line(x1, y0, x1, y1)   # right
        lines += line(x1, y1, x0, y1)   # bottom
        lines += line(x0, y1, x0, y0)   # left

    # ---- NPTH hole circles on Edge.Cuts (Ø3.2 mm) ----
    lines += ["G04 --- NPTH circles on Edge.Cuts (Ø3.2 mm) ---*",
              apt(11, "C", "0.120"),
              "D11*"]
    r_npth = MH_D / 2.0   # 1.6 mm
    for (cx, cy) in MH:
        # Draw circle as 4 quadrant arcs (G03 CCW full circle in 4 steps)
        # Start at right: (cx+r, cy)
        sx, sy = cx + r_npth, cy
        # Quarter 1: right → bottom  (cx+r,cy)→(cx,cy+r)  centre at (cx,cy)
        lines += [f"{coord(sx, sy)}D02*"]
        i0 = round((cx - sx)  * SCALE)
        j0 = round((cy - sy)  * SCALE)
        lines += [f"G03{coord(cx, cy + r_npth)}I{i0}J{j0}D01*"]
        i1 = round((cx - cx)  * SCALE)
        j1 = round((cy - (cy + r_npth)) * SCALE)
        lines += [f"G03{coord(cx - r_npth, cy)}I{i1}J{j1}D01*"]
        i2 = round((cx - (cx - r_npth)) * SCALE)
        j2 = round((cy - cy) * SCALE)
        lines += [f"G03{coord(cx, cy - r_npth)}I{i2}J{j2}D01*"]
        i3 = round((cx - cx) * SCALE)
        j3 = round((cy - (cy - r_npth)) * SCALE)
        lines += [f"G03{coord(sx, sy)}I{i3}J{j3}D01*"]

    lines += gerber_footer()
    return "\n".join(lines) + "\n"

# ---------------------------------------------------------------------------
# 2. Front Silkscreen  (TP-CAN-2I-F_Silkscreen.gto)
# ---------------------------------------------------------------------------
def build_f_silkscreen() -> str:
    lines = gerber_header("Legend,Top")
    lines += [
        "G04 --- Aperture definitions ---*",
        apt(10, "C", "0.150"),   # isolation barrier line  (0.2 mm → 0.15 min)
        apt(11, "C", "0.150"),   # mounting-hole silk rings
        apt(12, "C", "0.150"),   # general silk lines
        "G75*",
    ]

    # ---- Isolation-barrier vertical line: x=54, y=2..48 ----
    lines += [
        "G04 --- Galvanic isolation barrier line at x=54 mm ---*",
        "D10*",
        f"{coord(54.0, 2.0)}D02*",
        f"{coord(54.0, 48.0)}D01*",
    ]

    # ---- Channel-split horizontal line: x=54..70, y=24 ----
    lines += [
        "G04 --- Channel split line y=24 mm ---*",
        f"{coord(54.0, 24.0)}D02*",
        f"{coord(70.0, 24.0)}D01*",
    ]

    # ---- Mounting-hole silk rings  Ø3.0 mm circle ----
    lines += [
        "G04 --- Mounting hole silk rings (Ø3.0 mm) ---*",
        "D11*",
    ]
    r_silk = MH_SILK_R / 2.0  # 1.5 mm radius
    for (cx, cy) in MH:
        sx = cx + r_silk
        sy = cy
        lines += [f"{coord(sx, sy)}D02*"]
        i0 = round((cx - sx) * SCALE)
        j0 = 0
        lines += [f"G03{coord(cx, cy + r_silk)}I{i0}J{j0}D01*"]
        i1 = 0
        j1 = round((cy - (cy + r_silk)) * SCALE)
        lines += [f"G03{coord(cx - r_silk, cy)}I{i1}J{j1}D01*"]
        i2 = round((cx - (cx - r_silk)) * SCALE)
        j2 = 0
        lines += [f"G03{coord(cx, cy - r_silk)}I{i2}J{j2}D01*"]
        i3 = 0
        j3 = round((cy - (cy - r_silk)) * SCALE)
        lines += [f"G03{coord(sx, sy)}I{i3}J{j3}D01*"]

    # ---- Text annotations as %TF comment blocks (silkscreen text) ----
    # Full glyph stroking is omitted (no font data in this generator).
    # Instead, text content is declared via G04 comments and %TF attributes so
    # that the CAM operator and FAB_README.md carry the branding faithfully.
    # Physical text placement in KiCad will generate the real silkscreen glyphs
    # when the board is exported after routing.
    lines += [
        "G04 --- Silkscreen text elements (reference: rendered in KiCad export) ---*",
        "G04 TEXT @ (35.0, 49.3): TESTER PRESENT  TP-CAN-2I  Rev A*",
        "G04 TEXT @ (54.0, 24.0, rot90): <<  GALVANIC  ISOLATION  BARRIER  >>*",
        "G04 TEXT @ (24.0,  4.0): ANTENNA KEEP-OUT (no copper) ->*",
        "%TF.CreationDate,2026-06-01*%",
    ]

    lines += gerber_footer()
    return "\n".join(lines) + "\n"

# ---------------------------------------------------------------------------
# 3.  Copper / Mask placeholder layers
# ---------------------------------------------------------------------------
COPPER_LAYERS = [
    ("TP-CAN-2I-F_Cu.gtl",      "Copper,L1,Top"),
    ("TP-CAN-2I-In1_Cu.g2",     "Copper,L2,Inr"),
    ("TP-CAN-2I-In2_Cu.g3",     "Copper,L3,Inr"),
    ("TP-CAN-2I-B_Cu.gbl",      "Copper,L4,Bot"),
]

MASK_LAYERS = [
    ("TP-CAN-2I-F_Mask.gts",    "Soldermask,Top"),
    ("TP-CAN-2I-B_Mask.gbs",    "Soldermask,Bot"),
]

def build_placeholder(file_function: str) -> str:
    lines = gerber_header(file_function)
    lines += [
        "G04 placeholder: no copper/mask features defined yet.*",
        "G04 Complete these layers by running File > Fabrication Outputs > Gerbers*",
        "G04 inside KiCad after schematic capture, footprint placement, and routing.*",
    ]
    lines += gerber_footer()
    return "\n".join(lines) + "\n"

# ---------------------------------------------------------------------------
# 4.  NPTH Excellon drill file  (TP-CAN-2I-NPTH.drl)
# ---------------------------------------------------------------------------
def build_npth_drill() -> str:
    """Excellon NPTH drill file for 4x M3 holes Ø3.2 mm."""
    # Excellon metric trailing-zero format: coordinates in mm * 1000
    # METRIC,TZ means Trailing Zeros suppressed → leading zeros kept
    # e.g. X4000Y4000 = (4.000, 4.000) mm
    def ec(v: float) -> str:
        """Excellon coordinate: mm × 1000, no decimal point."""
        return str(round(v * 1000))

    out = [
        "M48",
        "METRIC,TZ",
        "; TP-CAN-2I NPTH drill file",
        "; 4 x M3 mounting holes  Diameter 3.200 mm",
        f"T1C{MH_D:.3f}",
        "%",          # end of header
        "G05",        # drill mode
        "T1",
    ]
    for (x, y) in MH:
        out.append(f"X{ec(x)}Y{ec(y)}")
    out.append("M30")
    return "\n".join(out) + "\n"

# ---------------------------------------------------------------------------
# 5.  Gerber Job JSON  (TP-CAN-2I.gbrjob)
# ---------------------------------------------------------------------------
def build_gbrjob() -> str:
    job = {
        "Header": {
            "GenerationSoftware": {
                "Vendor": "Tester Present Specialist Automotive Solutions",
                "Application": "generate_gerbers.py",
                "Version": "1.0"
            },
            "CreationDate": "2026-06-01T00:00:00Z",
            "ProjectId": {
                "Name": "TP-CAN-2I",
                "GUID": "tp-can-2i-gerber-job-2026",
                "Revision": "A"
            }
        },
        "GeneralSpecs": {
            "ProjectId": {
                "Name": "TP-CAN-2I",
                "GUID": "tp-can-2i-gerber-job-2026",
                "Revision": "A"
            },
            "Size": {"X": 70.0, "Y": 50.0},
            "LayerNumber": 4,
            "BoardThickness": 1.6,
            "Finish": "ENIG",
            "ImpedanceControlled": False
        },
        "DesignRules": [
            {
                "Layers": "Outer",
                "PadToPad": 0.2,
                "PadToTrack": 0.2,
                "TrackToTrack": 0.2,
                "MinLineWidth": 0.25
            },
            {
                "Layers": "Inner",
                "PadToPad": 0.2,
                "PadToTrack": 0.2,
                "TrackToTrack": 0.2,
                "MinLineWidth": 0.25
            }
        ],
        "FilesAttributes": [
            {
                "Path": "TP-CAN-2I-F_Cu.gtl",
                "FileFunction": "Copper,L1,Top",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-In1_Cu.g2",
                "FileFunction": "Copper,L2,Inr",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-In2_Cu.g3",
                "FileFunction": "Copper,L3,Inr",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-B_Cu.gbl",
                "FileFunction": "Copper,L4,Bot",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-F_Mask.gts",
                "FileFunction": "Soldermask,Top",
                "FilePolarity": "Negative"
            },
            {
                "Path": "TP-CAN-2I-B_Mask.gbs",
                "FileFunction": "Soldermask,Bot",
                "FilePolarity": "Negative"
            },
            {
                "Path": "TP-CAN-2I-F_Silkscreen.gto",
                "FileFunction": "Legend,Top",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-Edge_Cuts.gm1",
                "FileFunction": "Profile,NP",
                "FilePolarity": "Positive"
            },
            {
                "Path": "TP-CAN-2I-NPTH.drl",
                "FileFunction": "NonPlated,1,4,NPTH",
                "FilePolarity": "Positive"
            }
        ],
        "MaterialStackup": [
            {
                "Type": "Legend",
                "Color": "White",
                "Name": "F.SilkS"
            },
            {
                "Type": "SolderMask",
                "Color": "Black",
                "Thickness": 0.01,
                "Name": "F.Mask"
            },
            {
                "Type": "Copper",
                "Thickness": 0.035,
                "Name": "F.Cu"
            },
            {
                "Type": "Dielectric",
                "Material": "FR4",
                "Thickness": 0.21,
                "Name": "dielectric 1"
            },
            {
                "Type": "Copper",
                "Thickness": 0.017,
                "Name": "In1.Cu"
            },
            {
                "Type": "Dielectric",
                "Material": "FR4",
                "Thickness": 1.065,
                "Name": "core"
            },
            {
                "Type": "Copper",
                "Thickness": 0.017,
                "Name": "In2.Cu"
            },
            {
                "Type": "Dielectric",
                "Material": "FR4",
                "Thickness": 0.21,
                "Name": "dielectric 2"
            },
            {
                "Type": "Copper",
                "Thickness": 0.035,
                "Name": "B.Cu"
            },
            {
                "Type": "SolderMask",
                "Color": "Black",
                "Thickness": 0.01,
                "Name": "B.Mask"
            }
        ]
    }
    return json.dumps(job, indent=2) + "\n"

# ---------------------------------------------------------------------------
# 6.  LAYER_MAP.txt
# ---------------------------------------------------------------------------
def build_layer_map() -> str:
    return """\
TP-CAN-2I  Gerber / Drill Layer Map
=====================================
File                          KiCad Layer     Function                       Status
--------------------------    -----------     ------------------------------ --------------------
TP-CAN-2I-Edge_Cuts.gm1      Edge.Cuts       Board outline + milling slots  COMPLETE (geometry)
TP-CAN-2I-F_Silkscreen.gto   F.SilkS         Top silkscreen                 PARTIAL (rings/lines; text glyphs from KiCad)
TP-CAN-2I-F_Cu.gtl            F.Cu (L1)       Top copper signal              PLACEHOLDER
TP-CAN-2I-In1_Cu.g2           In1.Cu (L2)     Inner GND plane                PLACEHOLDER
TP-CAN-2I-In2_Cu.g3           In2.Cu (L3)     Inner PWR plane                PLACEHOLDER
TP-CAN-2I-B_Cu.gbl             B.Cu  (L4)     Bottom copper signal           PLACEHOLDER
TP-CAN-2I-F_Mask.gts           F.Mask          Top soldermask                 PLACEHOLDER
TP-CAN-2I-B_Mask.gbs           B.Mask          Bottom soldermask              PLACEHOLDER
TP-CAN-2I-NPTH.drl             --              NPTH Excellon drill            COMPLETE (4x M3)
TP-CAN-2I.gbrjob               --              Gerber Job JSON                COMPLETE

Stackup: 4-layer FR-4, 1.6 mm total, ENIG, black soldermask, white silkscreen
"""

# ---------------------------------------------------------------------------
# 7.  FAB_README.md
# ---------------------------------------------------------------------------
def build_fab_readme() -> str:
    return """\
# TP-CAN-2I — Fabrication Gerber Package README

> **CRITICAL: THIS IS A MECHANICAL/OUTLINE FABRICATION SET ONLY.**
> Copper (L1–L4) and soldermask layers are PLACEHOLDER FILES with no features.
> They carry valid RS-274X headers and end-of-file markers but contain zero
> traces, pads, or fills. **Do NOT send this package for PCB fabrication until
> routing is complete in KiCad.**

---

## Board Specification

| Parameter        | Value                                   |
|------------------|-----------------------------------------|
| Board name       | TP-CAN-2I (Programmable Dual-CAN Interface) |
| Revision         | A                                       |
| Dimensions       | 70.0 × 50.0 mm, 3 mm corner radius     |
| Layer count      | 4 (signal / GND / PWR / signal)         |
| Thickness        | 1.6 mm                                  |
| Material         | FR-4, Tg ≥ 150 °C                      |
| Copper           | 1 oz outer, 0.5 oz inner                |
| Surface finish   | ENIG                                    |
| Soldermask       | Matte black (both sides)                |
| Silkscreen       | White (top)                             |

## Stackup

```
L1  F.Cu      35 µm   signal + components (top)
    prepreg  ~0.21 mm
L2  In1.Cu    17 µm   GND plane (continuous reference)
    core     ~1.065 mm
L3  In2.Cu    17 µm   PWR plane (+3V3 / +5V pours)
    prepreg  ~0.21 mm
L4  B.Cu      35 µm   signal + ground pour (bottom)
Total ≈ 1.6 mm
```

## Features Present in This Package

1. **Board outline** — 70 × 50 mm rounded-rectangle (R=3 mm), 4 straight edges
   + 4 G03 CCW corner arcs in `TP-CAN-2I-Edge_Cuts.gm1`.
2. **Isolation milling slots** — two rectangular slot outlines on Edge.Cuts:
   - Slot 1 (under U9 CAN1 isolator): (57.3, 8.5) – (58.7, 15.5) mm
   - Slot 2 (under U10 CAN2 isolator): (57.3, 29.5) – (58.7, 36.5) mm
3. **NPTH mounting holes** — 4× M3, Ø3.2 mm at (4,4), (66,4), (4,46), (66,46)
   in `TP-CAN-2I-NPTH.drl` (Excellon METRIC,TZ).
4. **Silkscreen** (partial):
   - Isolation-barrier vertical line at x=54 mm, y=2–48 mm
   - Channel-split horizontal line at y=24 mm (x=54–70 mm)
   - Mounting-hole rings Ø3.0 mm (silk only, no copper)
   - Text labels noted as G04 comments; glyphs will be rendered by KiCad export.
5. **Gerber Job JSON** — 4-layer stackup, ENIG, black mask, white silk.

## What Is NOT in This Package (Requires KiCad Routing)

- Copper traces, planes, pours on any layer
- Pad definitions (SMT or through-hole)
- Soldermask openings
- Solder paste layers
- PTH drill file
- IPC-356 netlist
- Assembly drawing / pick-and-place

## Next Steps

1. Open `Hardware/KiCad/TP-CAN-2I.kicad_pcb` in KiCad 7+.
2. Import schematic (File > Update PCB from Schematic).
3. Assign footprints per `Hardware/BOM.csv`.
4. Place components per the Dwgs.User courtyard guides.
5. Route per `Hardware/Fabrication_Notes.md` and `.kicad_dru` rules.
6. Export Gerbers (File > Fabrication Outputs > Gerbers) replacing placeholders.
7. Export Excellon drill (PTH + NPTH).
8. Verify with a Gerber viewer (KiCad PCB editor or Gerber Viewer) before ordering.

---
Generated by `Hardware/Gerbers/generate_gerbers.py`
"""

# ---------------------------------------------------------------------------
# Validation helper
# ---------------------------------------------------------------------------
def validate_gerber(path: Path, tag: str):
    text = path.read_text(encoding="utf-8")
    errors = []
    if not text.startswith("%FSLAX46Y46*%"):
        errors.append("does not start with %FSLAX46Y46*%")
    if "%MOMM*%" not in text:
        errors.append("missing %MOMM*%")
    if not text.rstrip().endswith("M02*"):
        errors.append("does not end with M02*")
    # Check that every aperture used (Dnn* where nn>=10) is defined before use
    defined = set()
    for m in re.finditer(r'%ADD(\d+)', text):
        defined.add(int(m.group(1)))
    # Find all Dnn* draws/selects (not D01/D02/D03)
    used = set()
    for m in re.finditer(r'D(\d+)\*', text):
        code = int(m.group(1))
        if code >= 10:
            used.add(code)
    undefined = used - defined
    if undefined:
        errors.append(f"apertures used but not defined: {undefined}")
    if errors:
        print(f"  VALIDATION FAIL [{tag}]: {'; '.join(errors)}")
        return False
    print(f"  OK  {tag}")
    return True

def validate_excellon(path: Path, tag: str):
    text = path.read_text(encoding="utf-8")
    errors = []
    if not text.startswith("M48"):
        errors.append("does not start with M48")
    if "M30" not in text:
        errors.append("missing M30 end-of-file")
    if "T1C" not in text:
        errors.append("missing tool definition T1C")
    if errors:
        print(f"  VALIDATION FAIL [{tag}]: {'; '.join(errors)}")
        return False
    print(f"  OK  {tag}")
    return True

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    print("TP-CAN-2I Gerber generator")
    print(f"Output directory: {OUT}")
    OUT.mkdir(parents=True, exist_ok=True)

    files = {}  # filename -> content string

    # Edge Cuts
    files["TP-CAN-2I-Edge_Cuts.gm1"]     = build_edge_cuts()
    # Silkscreen
    files["TP-CAN-2I-F_Silkscreen.gto"]  = build_f_silkscreen()
    # Copper placeholders
    for fname, ff in COPPER_LAYERS:
        files[fname] = build_placeholder(ff)
    # Mask placeholders
    for fname, ff in MASK_LAYERS:
        files[fname] = build_placeholder(ff)
    # Excellon
    files["TP-CAN-2I-NPTH.drl"]          = build_npth_drill()
    # Gerber Job JSON
    files["TP-CAN-2I.gbrjob"]            = build_gbrjob()
    # Auxiliary text files
    files["LAYER_MAP.txt"]               = build_layer_map()
    files["FAB_README.md"]               = build_fab_readme()

    # Write all files
    for fname, content in files.items():
        fpath = OUT / fname
        fpath.write_text(content, encoding="utf-8")
        print(f"  wrote {fname}  ({len(content)} bytes)")

    # Validate Gerbers
    print("\nValidating Gerber files...")
    all_ok = True
    gerber_exts = {".gm1", ".gto", ".gtl", ".g2", ".g3", ".gbl", ".gts", ".gbs"}
    for fname in files:
        fpath = OUT / fname
        ext = Path(fname).suffix.lower()
        if ext in gerber_exts:
            all_ok &= validate_gerber(fpath, fname)
        elif ext == ".drl":
            all_ok &= validate_excellon(fpath, fname)

    # Zip
    zip_path = OUT / "TP-CAN-2I_Gerbers.zip"
    print(f"\nCreating {zip_path.name} ...")
    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for fname in files:
            zf.write(OUT / fname, arcname=fname)
    print(f"  zip contains {len(files)} files, size={zip_path.stat().st_size} bytes")

    print("\n--- Summary ---")
    print(f"Output: {OUT}")
    print(f"Validation {'PASSED' if all_ok else 'FAILED (see above)'}")
    print("CAVEAT: Copper (F_Cu, In1_Cu, In2_Cu, B_Cu) and soldermask (F_Mask, B_Mask)")
    print("layers are PLACEHOLDER RS-274X files with no features — complete them via")
    print("KiCad after schematic capture, footprint placement, and full routing.")
    return 0 if all_ok else 1

if __name__ == "__main__":
    raise SystemExit(main())
