%FSLAX46Y46*%
%MOMM*%
%TF.FileFunction,Soldermask,Top*%
%TF.FilePolarity,Positive*%
%TF.SameCoordinates,Original*%
G04 --- Generated by TP-CAN-2I generate_gerbers.py ---*
G04 placeholder: no copper/mask features defined yet.*
G04 Complete these layers by running File > Fabrication Outputs > Gerbers*
G04 inside KiCad after schematic capture, footprint placement, and routing.*
M02*
